version: '3'
services:
  backend:
    build:
      context: server
      dockerfile: ../server/Dockerfile

    ports:
      - '4000:4000'
    expose:
      - '4000'
  frontend:
    build:
      context: client
      dockerfile: ../client/Dockerfile
    ports:
      - '80:80'
    expose:
      - '80'
#
